//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upcDistribuidos.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_prestamo_det
    {
        public int pres_id { get; set; }
        public int mat_id { get; set; }
        public Nullable<byte> cant { get; set; }
    
        public virtual tb_material tb_material { get; set; }
        public virtual tb_prestamo tb_prestamo { get; set; }
    }
}
