//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upcDistribuidos.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_prestamo()
        {
            this.tb_prestamo_det = new HashSet<tb_prestamo_det>();
        }
    
        public int pres_id { get; set; }
        public int estado { get; set; }
        public System.DateTime fec_reserva { get; set; }
        public Nullable<System.DateTime> fec_ini_pre { get; set; }
        public Nullable<System.DateTime> fec_fin_pre { get; set; }
        public Nullable<System.DateTime> fec_devolucion { get; set; }
        public string observacion { get; set; }
        public int per_id { get; set; }
    
        public virtual tb_estado tb_estado { get; set; }
        public virtual tb_persona tb_persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_prestamo_det> tb_prestamo_det { get; set; }
    }
}
