//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upcDistribuidos.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public int usu_id { get; set; }
        public int per_id { get; set; }
        public string password { get; set; }
        public string perfil_id { get; set; }
    
        public virtual tb_persona tb_persona { get; set; }
    }
}
