//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace UnitTestProject1.contratoPersona {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Dominio")]
    public partial class Persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ApellidosField;
        
        private string CelularField;
        
        private string CodigoField;
        
        private string CorreoField;
        
        private decimal DeudaField;
        
        private string DireccionField;
        
        private int IdField;
        
        private string NombresField;
        
        private byte NroLibrosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Deuda {
            get {
                return this.DeudaField;
            }
            set {
                if ((this.DeudaField.Equals(value) != true)) {
                    this.DeudaField = value;
                    this.RaisePropertyChanged("Deuda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte NroLibros {
            get {
                return this.NroLibrosField;
            }
            set {
                if ((this.NroLibrosField.Equals(value) != true)) {
                    this.NroLibrosField = value;
                    this.RaisePropertyChanged("NroLibros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="contratoPersona.IPersonas")]
    public interface IPersonas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonas/PersonaCrear", ReplyAction="http://tempuri.org/IPersonas/PersonaCrearResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.contratoPersona.Persona> PersonaCrearAsync(UnitTestProject1.contratoPersona.Persona personaCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonas/PersonaModificar", ReplyAction="http://tempuri.org/IPersonas/PersonaModificarResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.contratoPersona.Persona> PersonaModificarAsync(UnitTestProject1.contratoPersona.Persona personaModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonas/PersonaObtener", ReplyAction="http://tempuri.org/IPersonas/PersonaObtenerResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.contratoPersona.Persona> PersonaObtenerAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonas/PersonaEliminar", ReplyAction="http://tempuri.org/IPersonas/PersonaEliminarResponse")]
        System.Threading.Tasks.Task PersonaEliminarAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonas/PersonaListar", ReplyAction="http://tempuri.org/IPersonas/PersonaListarResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UnitTestProject1.contratoPersona.Persona>> PersonaListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonasChannel : UnitTestProject1.contratoPersona.IPersonas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonasClient : System.ServiceModel.ClientBase<UnitTestProject1.contratoPersona.IPersonas>, UnitTestProject1.contratoPersona.IPersonas {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PersonasClient() : 
                base(PersonasClient.GetDefaultBinding(), PersonasClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPersonas.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonasClient(EndpointConfiguration endpointConfiguration) : 
                base(PersonasClient.GetBindingForEndpoint(endpointConfiguration), PersonasClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PersonasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PersonasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.contratoPersona.Persona> PersonaCrearAsync(UnitTestProject1.contratoPersona.Persona personaCrear) {
            return base.Channel.PersonaCrearAsync(personaCrear);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.contratoPersona.Persona> PersonaModificarAsync(UnitTestProject1.contratoPersona.Persona personaModificar) {
            return base.Channel.PersonaModificarAsync(personaModificar);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.contratoPersona.Persona> PersonaObtenerAsync(string codigo) {
            return base.Channel.PersonaObtenerAsync(codigo);
        }
        
        public System.Threading.Tasks.Task PersonaEliminarAsync(string codigo) {
            return base.Channel.PersonaEliminarAsync(codigo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UnitTestProject1.contratoPersona.Persona>> PersonaListarAsync() {
            return base.Channel.PersonaListarAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPersonas)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPersonas)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8408/Personas.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return PersonasClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPersonas);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return PersonasClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPersonas);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IPersonas,
        }
    }
}
