//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upcDistribuidos.Comun {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Estados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Estados() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("upcDistribuidos.Comun.Estados", typeof(Estados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta.
        /// </summary>
        public static string ALTA_Value {
            get {
                return ResourceManager.GetString("ALTA_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja.
        /// </summary>
        public static string BAJA_VALUE {
            get {
                return ResourceManager.GetString("BAJA_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string FLAG_ALTA {
            get {
                return ResourceManager.GetString("FLAG_ALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        public static string FLAG_BAJA {
            get {
                return ResourceManager.GetString("FLAG_BAJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        public static string RES_ANU {
            get {
                return ResourceManager.GetString("RES_ANU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        public static string RES_DEV {
            get {
                return ResourceManager.GetString("RES_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5.
        /// </summary>
        public static string RES_PEN {
            get {
                return ResourceManager.GetString("RES_PEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        public static string RES_PRE {
            get {
                return ResourceManager.GetString("RES_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string RES_RES {
            get {
                return ResourceManager.GetString("RES_RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -1.
        /// </summary>
        public static string Seleccionar_Cod {
            get {
                return ResourceManager.GetString("Seleccionar_Cod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -----Seleccionar-----.
        /// </summary>
        public static string Seleccionar_Value {
            get {
                return ResourceManager.GetString("Seleccionar_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -1.
        /// </summary>
        public static string Todos_Cod {
            get {
                return ResourceManager.GetString("Todos_Cod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ------Todos-----.
        /// </summary>
        public static string Todos_Value {
            get {
                return ResourceManager.GetString("Todos_Value", resourceCulture);
            }
        }
    }
}
