//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upcDistribuidos.ClienteProxy.UsuarioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioService.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ObtenerUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(upcDistribuidos.Entidades.Errores.ParametroException), Action="http://tempuri.org/IUsuarioService/ObtenerUsuarioParametroExceptionFault", Name="ParametroException", Namespace="http://schemas.datacontract.org/2004/07/upcDistribuidos.Entidades.Errores")]
        upcDistribuidos.Entidades.Entidades.Usuario ObtenerUsuario(string cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.Usuario> ObtenerUsuarioAsync(string cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/RegistrarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/RegistrarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(upcDistribuidos.Entidades.Errores.ParametroException), Action="http://tempuri.org/IUsuarioService/RegistrarUsuarioParametroExceptionFault", Name="ParametroException", Namespace="http://schemas.datacontract.org/2004/07/upcDistribuidos.Entidades.Errores")]
        [System.ServiceModel.FaultContractAttribute(typeof(upcDistribuidos.Entidades.Errores.RepetidoException), Action="http://tempuri.org/IUsuarioService/RegistrarUsuarioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/upcDistribuidos.Entidades.Errores")]
        upcDistribuidos.Entidades.Entidades.Usuario RegistrarUsuario(upcDistribuidos.Entidades.Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/RegistrarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.Usuario> RegistrarUsuarioAsync(upcDistribuidos.Entidades.Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/ListarUsuariosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(upcDistribuidos.Entidades.Errores.ParametroException), Action="http://tempuri.org/IUsuarioService/ListarUsuariosParametroExceptionFault", Name="ParametroException", Namespace="http://schemas.datacontract.org/2004/07/upcDistribuidos.Entidades.Errores")]
        upcDistribuidos.Entidades.Mapper.UsuarioListar[] ListarUsuarios(upcDistribuidos.Entidades.Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Entidades.Mapper.UsuarioListar[]> ListarUsuariosAsync(upcDistribuidos.Entidades.Entidades.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : upcDistribuidos.ClienteProxy.UsuarioService.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<upcDistribuidos.ClienteProxy.UsuarioService.IUsuarioService>, upcDistribuidos.ClienteProxy.UsuarioService.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public upcDistribuidos.Entidades.Entidades.Usuario ObtenerUsuario(string cod) {
            return base.Channel.ObtenerUsuario(cod);
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.Usuario> ObtenerUsuarioAsync(string cod) {
            return base.Channel.ObtenerUsuarioAsync(cod);
        }
        
        public upcDistribuidos.Entidades.Entidades.Usuario RegistrarUsuario(upcDistribuidos.Entidades.Entidades.Usuario usuario) {
            return base.Channel.RegistrarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.Usuario> RegistrarUsuarioAsync(upcDistribuidos.Entidades.Entidades.Usuario usuario) {
            return base.Channel.RegistrarUsuarioAsync(usuario);
        }
        
        public upcDistribuidos.Entidades.Mapper.UsuarioListar[] ListarUsuarios(upcDistribuidos.Entidades.Entidades.Usuario usuario) {
            return base.Channel.ListarUsuarios(usuario);
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Entidades.Mapper.UsuarioListar[]> ListarUsuariosAsync(upcDistribuidos.Entidades.Entidades.Usuario usuario) {
            return base.Channel.ListarUsuariosAsync(usuario);
        }
    }
}
