//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upcDistribuidos.Pruebas.PrestamoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrestamoListar", Namespace="http://schemas.datacontract.org/2004/07/upcDistribuidos.Entidades.Mapper")]
    [System.SerializableAttribute()]
    public partial class PrestamoListar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaDevolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaPrestamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEstado {
            get {
                return this.CodEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodEstadoField, value) != true)) {
                    this.CodEstadoField = value;
                    this.RaisePropertyChanged("CodEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPersona {
            get {
                return this.CodPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodPersonaField, value) != true)) {
                    this.CodPersonaField = value;
                    this.RaisePropertyChanged("CodPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaDevolucion {
            get {
                return this.FechaDevolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaDevolucionField, value) != true)) {
                    this.FechaDevolucionField = value;
                    this.RaisePropertyChanged("FechaDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaEntregaField, value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaPrestamo {
            get {
                return this.FechaPrestamoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaPrestamoField, value) != true)) {
                    this.FechaPrestamoField = value;
                    this.RaisePropertyChanged("FechaPrestamo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaReserva {
            get {
                return this.FechaReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaReservaField, value) != true)) {
                    this.FechaReservaField = value;
                    this.RaisePropertyChanged("FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prestamo", Namespace="http://schemas.datacontract.org/2004/07/upcDistribuidos.Entidades.Entidades")]
    [System.SerializableAttribute()]
    public partial class Prestamo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaDevolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaPrestamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private upcDistribuidos.Pruebas.PrestamoWS.Material[] MaterialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UsuarioCreacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaDevolucion {
            get {
                return this.FechaDevolucionField;
            }
            set {
                if ((this.FechaDevolucionField.Equals(value) != true)) {
                    this.FechaDevolucionField = value;
                    this.RaisePropertyChanged("FechaDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaPrestamo {
            get {
                return this.FechaPrestamoField;
            }
            set {
                if ((this.FechaPrestamoField.Equals(value) != true)) {
                    this.FechaPrestamoField = value;
                    this.RaisePropertyChanged("FechaPrestamo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaReserva {
            get {
                return this.FechaReservaField;
            }
            set {
                if ((this.FechaReservaField.Equals(value) != true)) {
                    this.FechaReservaField = value;
                    this.RaisePropertyChanged("FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public upcDistribuidos.Pruebas.PrestamoWS.Material[] Materiales {
            get {
                return this.MaterialesField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialesField, value) != true)) {
                    this.MaterialesField = value;
                    this.RaisePropertyChanged("Materiales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((this.PersonaField.Equals(value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsuarioCreacion {
            get {
                return this.UsuarioCreacionField;
            }
            set {
                if ((this.UsuarioCreacionField.Equals(value) != true)) {
                    this.UsuarioCreacionField = value;
                    this.RaisePropertyChanged("UsuarioCreacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/upcDistribuidos.Entidades.Entidades")]
    [System.SerializableAttribute()]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnioField, value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Editorial {
            get {
                return this.EditorialField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorialField, value) != true)) {
                    this.EditorialField = value;
                    this.RaisePropertyChanged("Editorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Flag {
            get {
                return this.FlagField;
            }
            set {
                if ((this.FlagField.Equals(value) != true)) {
                    this.FlagField = value;
                    this.RaisePropertyChanged("Flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoId {
            get {
                return this.TipoIdField;
            }
            set {
                if ((this.TipoIdField.Equals(value) != true)) {
                    this.TipoIdField = value;
                    this.RaisePropertyChanged("TipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrestamoWS.IPrestamoService")]
    public interface IPrestamoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoService/BuscarPrestamo", ReplyAction="http://tempuri.org/IPrestamoService/BuscarPrestamoResponse")]
        upcDistribuidos.Pruebas.PrestamoWS.PrestamoListar[] BuscarPrestamo(string codigo, string estado, string persona, System.DateTime fechaPresIni, System.DateTime fechaPresFin, System.DateTime fechaDevIni, System.DateTime fechaDevFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoService/BuscarPrestamo", ReplyAction="http://tempuri.org/IPrestamoService/BuscarPrestamoResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Pruebas.PrestamoWS.PrestamoListar[]> BuscarPrestamoAsync(string codigo, string estado, string persona, System.DateTime fechaPresIni, System.DateTime fechaPresFin, System.DateTime fechaDevIni, System.DateTime fechaDevFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoService/ObtenerPrestamo", ReplyAction="http://tempuri.org/IPrestamoService/ObtenerPrestamoResponse")]
        upcDistribuidos.Pruebas.PrestamoWS.Prestamo ObtenerPrestamo(string cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoService/ObtenerPrestamo", ReplyAction="http://tempuri.org/IPrestamoService/ObtenerPrestamoResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Pruebas.PrestamoWS.Prestamo> ObtenerPrestamoAsync(string cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoService/RegistrarPrestamo", ReplyAction="http://tempuri.org/IPrestamoService/RegistrarPrestamoResponse")]
        upcDistribuidos.Pruebas.PrestamoWS.Prestamo RegistrarPrestamo(upcDistribuidos.Pruebas.PrestamoWS.Prestamo prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoService/RegistrarPrestamo", ReplyAction="http://tempuri.org/IPrestamoService/RegistrarPrestamoResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Pruebas.PrestamoWS.Prestamo> RegistrarPrestamoAsync(upcDistribuidos.Pruebas.PrestamoWS.Prestamo prestamo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrestamoServiceChannel : upcDistribuidos.Pruebas.PrestamoWS.IPrestamoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrestamoServiceClient : System.ServiceModel.ClientBase<upcDistribuidos.Pruebas.PrestamoWS.IPrestamoService>, upcDistribuidos.Pruebas.PrestamoWS.IPrestamoService {
        
        public PrestamoServiceClient() {
        }
        
        public PrestamoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrestamoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public upcDistribuidos.Pruebas.PrestamoWS.PrestamoListar[] BuscarPrestamo(string codigo, string estado, string persona, System.DateTime fechaPresIni, System.DateTime fechaPresFin, System.DateTime fechaDevIni, System.DateTime fechaDevFin) {
            return base.Channel.BuscarPrestamo(codigo, estado, persona, fechaPresIni, fechaPresFin, fechaDevIni, fechaDevFin);
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Pruebas.PrestamoWS.PrestamoListar[]> BuscarPrestamoAsync(string codigo, string estado, string persona, System.DateTime fechaPresIni, System.DateTime fechaPresFin, System.DateTime fechaDevIni, System.DateTime fechaDevFin) {
            return base.Channel.BuscarPrestamoAsync(codigo, estado, persona, fechaPresIni, fechaPresFin, fechaDevIni, fechaDevFin);
        }
        
        public upcDistribuidos.Pruebas.PrestamoWS.Prestamo ObtenerPrestamo(string cod) {
            return base.Channel.ObtenerPrestamo(cod);
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Pruebas.PrestamoWS.Prestamo> ObtenerPrestamoAsync(string cod) {
            return base.Channel.ObtenerPrestamoAsync(cod);
        }
        
        public upcDistribuidos.Pruebas.PrestamoWS.Prestamo RegistrarPrestamo(upcDistribuidos.Pruebas.PrestamoWS.Prestamo prestamo) {
            return base.Channel.RegistrarPrestamo(prestamo);
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Pruebas.PrestamoWS.Prestamo> RegistrarPrestamoAsync(upcDistribuidos.Pruebas.PrestamoWS.Prestamo prestamo) {
            return base.Channel.RegistrarPrestamoAsync(prestamo);
        }
    }
}
