//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upcDistribuidos.ClienteProxy.MaestroService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaestroService.IMaestroService")]
    public interface IMaestroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaestroService/ListarEstados", ReplyAction="http://tempuri.org/IMaestroService/ListarEstadosResponse")]
        upcDistribuidos.Entidades.Entidades.Estado[] ListarEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaestroService/ListarEstados", ReplyAction="http://tempuri.org/IMaestroService/ListarEstadosResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.Estado[]> ListarEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaestroService/ListarTipoMateriales", ReplyAction="http://tempuri.org/IMaestroService/ListarTipoMaterialesResponse")]
        upcDistribuidos.Entidades.Entidades.TipoMaterial[] ListarTipoMateriales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaestroService/ListarTipoMateriales", ReplyAction="http://tempuri.org/IMaestroService/ListarTipoMaterialesResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.TipoMaterial[]> ListarTipoMaterialesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaestroService/ListarCategorias", ReplyAction="http://tempuri.org/IMaestroService/ListarCategoriasResponse")]
        upcDistribuidos.Entidades.Entidades.Categoria[] ListarCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaestroService/ListarCategorias", ReplyAction="http://tempuri.org/IMaestroService/ListarCategoriasResponse")]
        System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.Categoria[]> ListarCategoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaestroServiceChannel : upcDistribuidos.ClienteProxy.MaestroService.IMaestroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaestroServiceClient : System.ServiceModel.ClientBase<upcDistribuidos.ClienteProxy.MaestroService.IMaestroService>, upcDistribuidos.ClienteProxy.MaestroService.IMaestroService {
        
        public MaestroServiceClient() {
        }
        
        public MaestroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaestroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaestroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaestroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public upcDistribuidos.Entidades.Entidades.Estado[] ListarEstados() {
            return base.Channel.ListarEstados();
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.Estado[]> ListarEstadosAsync() {
            return base.Channel.ListarEstadosAsync();
        }
        
        public upcDistribuidos.Entidades.Entidades.TipoMaterial[] ListarTipoMateriales() {
            return base.Channel.ListarTipoMateriales();
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.TipoMaterial[]> ListarTipoMaterialesAsync() {
            return base.Channel.ListarTipoMaterialesAsync();
        }
        
        public upcDistribuidos.Entidades.Entidades.Categoria[] ListarCategorias() {
            return base.Channel.ListarCategorias();
        }
        
        public System.Threading.Tasks.Task<upcDistribuidos.Entidades.Entidades.Categoria[]> ListarCategoriasAsync() {
            return base.Channel.ListarCategoriasAsync();
        }
    }
}
